### ISSUE TITLE
Error during installation on database

### ISSUE THREAD

**Issue by TJMusiitwa** [eemp/moodle#2]
Hello there I seem to be running into an issue during installation via heroku especially whilst setting up the database.

> Debug info: ERROR: column d.adsrc does not exist
LINE 1: ...e, a.attlen, a.atttypmod, a.attnotnull, a.atthasdef, d.adsrc
^
SELECT a.attnum, a.attname AS field, t.typname AS type, a.attlen, a.atttypmod, a.attnotnull, a.atthasdef, d.adsrc
FROM pg_catalog.pg_class c
JOIN pg_catalog.pg_namespace as ns ON ns.oid = c.relnamespace
JOIN pg_catalog.pg_attribute a ON a.attrelid = c.oid
JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
LEFT JOIN pg_catalog.pg_attrdef d ON (d.adrelid = c.oid AND d.adnum = a.attnum)
WHERE relkind = 'r' AND c.relname = 'mdl_config' AND c.reltype > 0 AND a.attnum > 0
AND (ns.nspname = current_schema() OR ns.oid = pg_my_temp_schema())
ORDER BY a.attnum
[NULL]
Error code: dmlreadexception

And as such I am unable to continue with the set up on restarting the dynos it returrns the following prompt:

> Config table does not contain version, can not continue, sorry.
More information about this error
It is usually not possible to recover from errors triggered during installation, you may need to create a new database or use a different database prefix if you want to retry the installation.

Please advise!

**Comment by eemp** [comment]
That means that moodle ran into an issue configuring the database during initial setup.  I believe your only option is to scrap the database and start over.

**Comment by TJMusiitwa** [comment]
I will give it a shot and let you know

Jonathan Musiitwa

________________________________

**Comment by TJMusiitwa** [comment]
Hey so I tried resetting the database on heroku and then re-ran the deploy.
So on-top of the above error; the following error is also returned

> Stack trace:

    line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 242 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    line 406 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 916 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->get_columns()
    line 1408 of /lib/moodlelib.php: call to pgsql_native_moodle_database->insert_record()
    line 1482 of /lib/upgradelib.php: call to set_config()
    line 1724 of /lib/upgradelib.php: call to upgrade_started()
    line 276 of /admin/index.php: call to install_core()

So do I then have to delete the Heroku Postgres Add-on and retry that?

**Comment by eemp** [comment]
I suspect that this is likely due to the moodle source code using old postgres functionality.

You can try the following:

* See if you can run on older versions of PG
* Try to apply the changes I have made to a more recent release of moodle

References:

* https://moodle.org/mod/forum/discuss.php?d=274077
* https://github.com/iomad/iomad/issues/1026
* http://www.edugeek.net/forums/virtual-learning-platforms/204223-moodle-database-read-error-post-migration.html
* https://www.webhostinghub.com/help/community/moodle/error-reading-database
* https://h5p.org/node/455745

**Comment by eemp** [comment]
I went ahead with the second suggestion and updated the default branch of this fork to `MOODLE_38_STABLE-heroku-compatible` (applied the necessary heroku updates to a more recent release branch from upstream)

**Comment by TJMusiitwa** [comment]
![image](https://user-images.githubusercontent.com/28179360/83749352-18fdbd00-a653-11ea-90f3-22585e85cf9a.png)

So I reforked the new repo and while the whole installation happened, the following came up.
Did I need to wait or is there a need for a new fix?

**Comment by eemp** [comment]
I believe when the installation is happening (you see that the site is being upgraded), you must wait it out and avoid any restarts/etc.  Otherwise, the db is dirty and you run into issues such as those.

It also looks like moodle is less and less friendly to this simply git push and deploy to heroku approach.

**Comment by TJMusiitwa** [comment]
I try to avoid that but as you know with heroku and its 30 minutes inactive shutdown time doesn't grant that luxury of just leaving it to install for more than 12 hours then come back to complete the installation process

Jonathan Musiitwa

________________________________
